### PR TITLE
Added skeleton app

### LINKED ISSUE #1: Create the skeleton app
Probably similar to LORE

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #1 

We also need to add a 'Needs Review' tag

### CODE REVIEW

**Comment by noisecapella** [comment]
Can you give this a review @jamiefolsom?

**Comment by jamiefolsom** [comment]
Sure.

**Comment by jamiefolsom** [comment]
First issue, as you know, is, at least on a mac, running a certain version of docker, and with lore using the same boot2docker-vm, we appear to be running out of space on the docker vm volume, and/or not being able to start postgres. Investigating now.

**Comment by pwilkins** [comment]
Docker very recently announced version 1.9.  Would a newer Docker version resolve the problem?  I'll volunteer to help with the testing the new version if I can reproduce the problem.

**Comment by jamiefolsom** [comment]
I just upgraded to 1.9.0, and have now gotten the TP app running. There are a few things in our configuration for LORE and TP that don't work with the new toolbox, but they're not show stoppers.

**Comment by jamiefolsom** [comment]
OK, so this is working for me. I can't reliably recall the sequence of docker commands, but I think it's:
```
docker-machine start default
docker-machine env default
eval "$(docker-machine env default)"
docker-compose up
```
And the IP is: http://192.168.99.100:8075/

YMMV. :+1: to merge, and let's keep moving. @noisecapella

**Pull request merged**
